export const styles = {
  loginPage: {
    width: "100%",
    minHeight: "calc(100vh - 64px)",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
  },
  loginLeft: {
    flex: "1 1 50%",
    display: "flex",
    flexDirection: "column",
  },
  loginRight: {
    flex: "1 1 50%",
    backgroundColor: "#f5f5f5",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  logo: {
    fontFamily: "Lato",
    color: "#3DBC57",
    fontWeight: "bolder",
    textDecoration: "none",
    display: "flex",
    textAlign: "left",
    fontSize: "60px",
    ml: "10%",
  },
  logoText: {
    marginLeft: "10%",
    marginRight: "10%",
  },
  loginHeader: {
    marginTop: "7%",
    marginBottom: "5%",
    marginLeft: "13%",
  },
  loginHeaderText: {
    fontSize: "30px",
    fontWeight: "bold",
    textAlign: "left",
  },
  loginErrorMessage: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "red",
  },
  loginSuccessMessage: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "green",
  },
  loginForm: {
    mt: 1,
    width: "80%",
  },
  loginForgotPasswordContainer: {
    display: "flex",
    justifyContent: "flex-end",
  },
  loginForgotPasswordText: {
    textDecoration: "none",
    color: "#3DBC57",
    fontWeight: "bold",
    marginTop: "2%",
  },
  loginSubmitButton: {
    background: "#3DBC57",
    color: "#fff",
    textTransform: "none",
    fontSize: "15px",
    mt: "10%",
    mb: 2,
    ml: "15%",
  },
  loginContainerOne: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  loginContainerTwo: {
    display: "flex",
    flexDirection: "column",
    marginLeft: "15%",
  },
  loginCreateAccountBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    marginLeft: "15%",
  },
  loginCreateAccountText: {
    color: "#3DBC57",
    fontWeight: "500",
    marginTop: "2%",
    textAlign: "center",
    fontSize: "15px",
  },
};
